name: CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-22.04  # Use the latest stable Ubuntu runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Fetch the latest code from the repository

      - name: Set Up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Verify Python Version
        run: python --version

      - name: Install Dependencies
        run: |
          cd backend
          python -m venv venv  # Create a virtual environment
          source venv/bin/activate  # Activate the virtual environment
          pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          pip install --no-cache-dir torch --index-url https://download.pytorch.org/whl/cpu  # Install only CPU version of PyTorch

      - name: Run Tests
        run: |
          cd backend
          source venv/bin/activate
          export PYTHONPATH=$(pwd)
          pytest  # Run unit tests

      - name: Free Up Disk Space
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          docker image prune -af  # Remove unused Docker images
          df -h  # Display free disk space

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Deploy FastAPI App
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_MODEL_NAME: "SentimentModel"
          MLFLOW_MODEL_VERSION: "latest"
        run: |
          cd backend
          model_uri="models:/${MLFLOW_MODEL_NAME}/${MLFLOW_MODEL_VERSION}"
          echo "Deploying model from ${model_uri} to FastAPI service"
          docker build --no-cache -t fastapi-app .
          docker-compose up -d  # Start FastAPI in detached mode

      - name: Notify Result
        if: success()
        run: echo "Deployment successful!" || echo "Deployment failed!"
