name: CD Pipeline

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # The CI/CD runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd backend
          source venv/bin/activate
          pytest

      - name: Deploy FastAPI App
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_MODEL_NAME: "SentimentModel"
          MLFLOW_MODEL_VERSION: "latest"
        run: |
          cd backend
          model_uri="models:/${MLFLOW_MODEL_NAME}/${MLFLOW_MODEL_VERSION}"
          echo "Deploying model from ${model_uri} to FastAPI service"

          docker build -t fastapi-app .
          docker-compose up -d  # Start FastAPI in detached mode

      - name: Notify result
        if: success()
        run: echo "Deployment successful!" || echo "Deployment failed!"
