name: CI

on:
  push:
    branches:
      - main  # Change this to your default branch if different
  pull_request:
    branches:
      - main  # Change this to your default branch if different

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          echo "Current directory before entering backend:"
          pwd
          ls -l
          cd backend  # Change to the backend directory
          echo "Current directory inside backend before installing dependencies:"
          pwd
          ls -l
          python -m venv venv  # Create a virtual environment
          source venv/bin/activate  # Activate the virtual environment
          pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies

      - name: Install torch explicitly
        run: |
          source backend/venv/bin/activate
          pip install torch --index-url https://download.pytorch.org/whl/cpu  # Adjust based on GPU/CPU

      - name: Run tests
        run: |
          echo "Current directory before running tests:"
          pwd
          ls -l
          cd backend  # Change to the backend directory
          echo "Current directory inside backend before executing tests:"
          pwd
          ls -l
          source venv/bin/activate  # Activate the virtual environment
          export PYTHONPATH=$(pwd)  # Add backend directory to PYTHONPATH
          echo "PYTHONPATH set to: $PYTHONPATH"
          pytest  # Run your tests

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
