name: CI Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow when there are pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow when there's a pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # The CI/CD runner that will execute the job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.21'  # Specify Python version

      - name: Install dependencies
        run: |
          python -m venv venv  # Create a virtual environment
          source venv/bin/activate
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest  # Run tests (ensure you have test files for FastAPI)

      - name: Lint code
        run: |
          source venv/bin/activate
          pip install flake8  # Install flake8 for code linting
          flake8 .  # Run linting on the entire codebase

      - name: Check for security vulnerabilities
        run: |
          source venv/bin/activate
          pip install safety  # Install safety tool for security checks
          safety check  # Run security vulnerability checks

      - name: Notify success
        run: echo "CI Pipeline executed successfully!"  # Optionally notify when successful

      - name: Notify failure
        if: failure()  # Notify on failure
        run: echo "CI Pipeline failed!"
