name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to latest version

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to latest version
        with:
          python-version: '3.9'  # Use '3.9' instead of '3.9.21' for flexibility

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt pytest flake8 safety  # Install required tools

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest

      - name: Lint code
        run: |
          source venv/bin/activate
          flake8 .

      - name: Check for security vulnerabilities
        run: |
          source venv/bin/activate
          safety check

      - name: Notify success
        if: success()
        run: echo "✅ CI Pipeline executed successfully!"

      - name: Notify failure
        if: failure()
        run: echo "❌ CI Pipeline failed!"
