name: CI

on:
  push:
    branches:
      - main  # Adjust this if your default branch is different
  pull_request:
    branches:
      - main  # Adjust this if your default branch is different

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          echo "Current directory before entering backend:"
          pwd
          ls -l
          cd backend  # Change to the backend directory
          echo "Current directory inside backend before installing dependencies:"
          pwd
          ls -l
          python -m venv venv  # Create a virtual environment
          source venv/bin/activate && exec bash  # Activate the virtual environment
          pip install --upgrade pip  # Upgrade pip
          pip install --no-cache-dir -r requirements.txt  # Install dependencies
          pip install --no-cache-dir torch --index-url https://download.pytorch.org/whl/cpu  # Install PyTorch separately

      - name: Run tests
        run: |
          cd backend
          source venv/bin/activate && exec bash  # Activate virtual environment
          export PYTHONPATH=$(pwd)
          pytest  # Run tests
