name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest

      - name: Lint code
        run: |
          source venv/bin/activate
          pip install flake8
          flake8 .

      - name: Check for security vulnerabilities
        run: |
          source venv/bin/activate
          pip install safety
          safety check

      - name: Notify success
        run: echo "CI Pipeline executed successfully!"

      - name: Notify failure
        if: failure()
        run: echo "CI Pipeline failed!"