name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Ensure latest version is used

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Downgraded from 3.12 for better compatibility

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools wheel  # Ensure latest pip tools
          pip install numpy==1.26.0  # Install NumPy first to prevent conflicts
          pip install -r requirements.txt  # Install all other dependencies

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest backend/tests

      - name: Lint code
        run: |
          source venv/bin/activate
          flake8 .

      - name: Check for security vulnerabilities
        run: |
          source venv/bin/activate
          safety check

      - name: Notify success
        if: success()
        run: echo "✅ CI Pipeline executed successfully!"

      - name: Notify failure
        if: failure()
        run: echo "❌ CI Pipeline failed!"
